FROM phpdoc/phpdoc:3.5 AS doc_builder

COPY . /source

WORKDIR /source

RUN mkdir /target && \
    phpdoc run \
        -d 'core/classes' \
        -d 'modules/Core/classes' \
        -d 'modules/Forum/classes' \
        -i vendor \
        -t /target

FROM nginxinc/nginx-unprivileged:stable

COPY --from=doc_builder /target /usr/share/nginx/html
